{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.api.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.ingress.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.api.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "sm-resource-manager.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: "{{ default (printf "api-%s.%s" (include "sm-resource-manager.fullname" .) .Values.ingress.zone) .Values.ingress.api.host }}"
      http:
        paths:
          - path: "/v1/transcribers"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "sm-resource-manager.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - "*.{{ .Values.ingress.zone }}"
      secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  {{- if (and .Values.ingress.enableRedirectAnnotations .Values.ingress.ingressClassName) }}
  {{- .Files.Get (printf "redirects/%s.yaml" .Values.ingress.ingressClassName) | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.redirect.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.redirect.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "sm-resource-manager.fullname" . }}-redirect
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: "{{ default (printf "transcribe-%s.%s" (include "sm-resource-manager.fullname" .) .Values.ingress.zone) .Values.ingress.redirect.host }}"
      http:
        paths:
          - path: {{ .Values.ingress.redirect.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "sm-resource-manager.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - "*.{{ .Values.ingress.zone }}"
      secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
{{- if .Values.ingress.flow.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  {{- if (and .Values.ingress.enableRedirectAnnotations .Values.ingress.ingressClassName) }}
  {{- .Files.Get (printf "redirects/%s.yaml" .Values.ingress.ingressClassName) | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.flow.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.flow.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "sm-resource-manager.fullname" . }}-flow
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: "{{ default (printf "%s.%s" (include "sm-resource-manager.fullname" .) .Values.ingress.zone) .Values.ingress.flow.host }}"
      http:
        paths:
          - path: /v1/flow
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "sm-resource-manager.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - "*.{{ .Values.ingress.zone }}"
      secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
