{{- if .Values.reconciliation.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "sm-resource-manager.fullname" . }}-reconciliation"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sm-resource-manager.labels" (merge (dict "app" "reconciliation") .) | nindent 4 }}
  annotations:
    {{- include "sm-resource-manager.annotations" . | nindent 4 }}
spec:
  # replicas has to be 1 or repopulation will have issues
  replicas: 1
  selector:
    matchLabels:
      {{- include "sm-resource-manager.selectorLabels" (merge (dict "app" "reconciliation") .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sm-resource-manager.selectorLabels" (merge (dict "app" "reconciliation") .) | nindent 8 }}
        {{- with .Values.reconciliation.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.reconciliation.additionalAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: reconciliation
          image: {{ include "sm-resource-manager.image" (dict "Chart" .Chart "global" .Values.global.resourceManager "component" .Values.reconciliation) | quote }}
          env:
            - name: SM_K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: REDIS_CONN_URL
              valueFrom:
              {{- if not .Values.externalRedis.enabled }}
                configMapKeyRef:
                  name: {{ default (printf "%s-config" (include "sm-resource-manager.fullname" .)) .Values.redis.configMap.name }}
                  key: redis_url
              {{- else }}
                secretKeyRef:
                  name: {{ include "sm-resource-manager.redisSecretName" . }}
                  key: redis_url
            - name: REDIS_USE_EXTERNAL
              value: "true"
            - name: REDIS_DB_INDEX
              value: {{ default 0 .Values.externalRedis.dbIndex | quote }}
              {{- end }}
            - name: REDIS_FAIL_OVER_CLIENT_ENABLED
              value: {{ default (and .Values.redis.sentinel.enabled (not .Values.externalRedis.enabled)) .Values.redis.failOverClientEnabled | quote }}
            {{- with .Values.redis.connectionTimeout }}
            - name: REDIS_SETUP_TIMEOUT_DURATION
              value: {{ . | quote }}
            {{- end }}
            - name: SM_RECONCILIATION_DRY_RUN_ONLY
              value: {{ default false .Values.reconciliation.dryRun | quote }}
            - name: SM_POD_SELECTOR_LIST
            {{- if .Values.reconciliation.podSelectorConfigMap.enabled }}
              valueFrom:
                configMapKeyRef:
                  name: {{ default .Release.Name .Values.reconciliation.podSelectorConfigMap.name }}
                  key: pod_selector_list
            {{- else }}
              value: {{ join "," .Values.reconciliation.podSelectorList }}
            {{- end }}
            - name: SM_TOKEN_STORE_RECONCILIATION_INTERVAL
              value: {{ .Values.reconciliation.reconciliationInterval }}s
            - name: SM_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  key: cluster_name
                  name: "{{ include "sm-resource-manager.fullname" . }}-config"
            - name: REPOPULATION_ENABLED
              value: {{ .Values.reconciliation.repopulation.enabled | quote }}
            {{- if .Values.reconciliation.repopulation.enabled }}
            - name: SM_DB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  key: conn_string
                  name: {{ include "sm-resource-manager.databaseSecretName" . }}
            - name: SG_CONTROLLER_ADDRESS
              value: {{ printf "http://%s" (include "sm-resource-manager.sessiongroups-controller.fullname" .) }}
            - name: SG_CONTROLLER_PAUSE_DURATION
              value: {{ (default "2s" .Values.reconciliation.repopulation.pauseDuration) | quote }}
            {{- end }}
            {{- if .Values.reconciliation.nodeMonitor.enabled }}
            - name: SM_NODE_MONITOR_ENABLED
              value: "true"
            - name: SM_NODE_MONITOR_CPU_THRESHOLD
              value: {{ .Values.reconciliation.nodeMonitor.cpuThreshold | quote }}
            - name: SM_NODE_MONITOR_CONDITION_DURATION
              value: {{ .Values.reconciliation.nodeMonitor.conditionDuration | quote }}
            - name: SM_NODE_MONITOR_NODE_LABELS
              value: {{ .Values.reconciliation.nodeMonitor.filterLabels | toJson | squote  }}
            {{- else }}
            - name: SM_NODE_MONITOR_ENABLED
              value: "false"
            {{- end }}
            {{- with .Values.reconciliation.additionalEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.reconciliation.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.reconciliation.containerPort }}
              name: http
              protocol: TCP
      serviceAccountName: {{ include "sm-resource-manager.fullname" . }}-metrics
      {{- with .Values.reconciliation.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
