---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sm-flow.configMapName" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- with (include "sm-flow.sysDefault" .) }}
  extra_config.yaml: |-
{{- . | nindent 4 }}
{{- end }}
