---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sm-resource-manager.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}-pod-reader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}-kube-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sm-resource-manager.fullname" . }}-pod-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "system:serviceaccount:{{ .Release.Namespace }}:{{ include "sm-resource-manager.fullname" . }}"
{{- if .Values.sessionGroups.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}-sessiongroups-reader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - speechmatics.com
    resources:
      - sessiongroups
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}-sessiongroups-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sm-resource-manager.fullname" . }}-sessiongroups-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "system:serviceaccount:{{ .Release.Namespace }}:{{ include "sm-resource-manager.fullname" . }}"
{{- end }}
{{- if (or .Values.metrics.enabled .Values.reconciliation.enabled) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sm-resource-manager.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}-list-workloads
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - watch
      - list
  - apiGroups: [""]
    resources:
      - "pods/status"
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}-metrics-permissions
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sm-resource-manager.fullname" . }}-list-workloads
subjects:
  - kind: ServiceAccount
    name: {{ include "sm-resource-manager.fullname" . }}-metrics
---
{{- if .Values.reconciliation.nodeMonitor.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-reconciliation-node-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-sessiongroups-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "sm-resource-manager.fullname" . }}-metrics
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- if .Values.metrics.workerMonitor.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}-access-cadvisor
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes/metrics", "nodes/stats"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}-metrics-cadvisor-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sm-resource-manager.fullname" . }}-access-cadvisor
subjects:
  - kind: ServiceAccount
    name: {{ include "sm-resource-manager.fullname" . }}-metrics
    namespace: {{ .Release.Namespace }}
{{- end }}