---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sm-resource-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sm-resource-manager.labels" (merge (dict "app" "resource-manager") .) | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "sm-resource-manager.selectorLabels" (merge (dict "app" "resource-manager") .) | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "sm-resource-manager.fullname" . }}-metrics"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sm-resource-manager.labels" (merge (dict "app" "metrics") .) | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: http
  selector:
    {{- include "sm-resource-manager.selectorLabels" (merge (dict "app" "metrics") .) | nindent 4 }}
