{{- if (default .Values.global.sessionGroups.enabled .Values.sessionGroups.enabled) }}
{{- $mode := (required "Please specify triton server mode (can be either batch, rt or translation)" .Values.tritonServer.mode) }}
{{- $op := .Values.tritonServer.operatingPoint }}
{{- $recipe := .Values.tritonServer.recipe }}
{{- $version := (include "sm-gpu.appVersion" .) }}
{{- $name := include "sm-gpu.fullname" . }}
{{- $containerName := include "sm-gpu.containerName" (dict "mode" $mode) }}
{{- $inferenceSidecarPort := default 8008 .Values.inferenceSidecar.port }}
---
apiVersion: speechmatics.com/v1
kind: SessionGroup
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "sm-gpu.annotations" . | nindent 4 }}
    tags.datadoghq.com/triton-server.service: {{ $name }}
    tags.datadoghq.com/triton-server.version: {{ $version | trunc 63 | quote }}
    {{- if ne "translation" $mode }}
    tags.datadoghq.com/triton-server.recipe: {{ $recipe | quote }}
    {{- end }}
    {{- with .Values.additionalAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    mode: {{ $mode }}
    {{- include "sm-gpu.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.sessionGroups.replicas }}
  allowedSurge: {{.Values.sessionGroups.allowedSurge}}
  maxPodsCreateAtOnce: {{.Values.sessionGroups.maxPodsCreateAtOnce}}
  strategyRecreate: {{ .Values.sessionGroups.strategyRecreate }}
  scaling:
    enabled: {{ default .Values.global.sessionGroups.scaling.enabled .Values.sessionGroups.scaling.enabled }}
    minReplicas: {{.Values.sessionGroups.scaling.minReplicas}}
    maxReplicas: {{.Values.sessionGroups.scaling.maxReplicas}}
    scaleDownDelay: {{.Values.sessionGroups.scaling.scaleDownDelay}}
    {{- if hasKey .Values.sessionGroups.scaling "scaleOnPodsLeft"}}
    scaleOnPodsLeft: {{.Values.sessionGroups.scaling.scaleOnPodsLeft}}
    {{- else if hasKey .Values.sessionGroups.scaling "scaleOnCapacityLeft"}}
    scaleOnCapacityLeft: {{.Values.sessionGroups.scaling.scaleOnCapacityLeft}}
    {{- else }}
      {{- fail "One value from sessionGroups.scaling.scaleOnPodsLeft or sessionGroups.scaling.scaleOnCapacityLeft must be set." }}
    {{- end }}
    maxPodsScaledDownAtOnce: {{.Values.sessionGroups.scaling.maxPodsScaledDownAtOnce}}
    {{- if hasKey .Values.sessionGroups.scaling "timeOfDay" }}
    timeOfDay:
      {{- toYaml .Values.sessionGroups.scaling.timeOfDay | nindent 6}}
    {{- end }}
  defrag:
    # This shouldn't be enabled on inference servers as we only ever have one pod per node
    enabled: false
    maxIdlePodsOnScaleUp: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $name }}
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      annotations:
        tags.datadoghq.com/triton-server.service: {{ $name }}
        tags.datadoghq.com/triton-server.version: {{ $version | trunc 63 | quote }}
        {{- if ne "translation" $mode }}
        tags.datadoghq.com/triton-server.recipe: {{ $recipe | quote }}
        {{- end }}
        {{- with .Values.tritonServer.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.datadog.addAnnotations }}
        {{- include "sm-gpu.tritonServerDatadogAnnotations" (dict "containerName" $containerName "name" $name "metrics" .Values.datadog.tritonServerMetrics) | nindent 8 }}
        {{- if .Values.inferenceSidecar.enabled }}
        {{- include "sm-gpu.inferenceSidecarDatadogAnnotations" (dict "port" $inferenceSidecarPort "metrics" .Values.datadog.inferenceSidecarMetrics) | nindent 8 }}
        {{- end }}
        {{- end }}
      labels:
        speechmatics.io/safe-to-evict: "false"
        mode: {{ $mode }}
        {{- include "sm-gpu.selectorLabels" . | nindent 8 }}
        {{- with .Values.tritonServer.additionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tritonServer.nodeSelector }}
      nodeSelector:
      {{- range $selector, $value := . }}
        {{ $selector }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- with .Values.tritonServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $containerName }}
          image: {{ include "sm-gpu.image" (dict "Chart" .Chart "global" .Values.global.transcriber "component" .Values.tritonServer) | quote }}
          command: {{ default "" .Values.tritonServer.command }}
          args: {{ default "" .Values.tritonServer.args }}
          env:
            - name: NVIDIA_REQUIRE_CUDA
              value: "cuda>=11.6"
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
          {{- if ne "translation" $mode }}
            - name: SM_BATCH_MODE
              value: {{ eq "batch" $mode | quote }}
          {{- if $op }}
            - name: SM_OPERATING_POINT
              value: {{ $op }}
          {{- end }}
          {{- end }}
            - name: SM_LICENSE_FILE
              value: /etc/secrets/license.json
          {{- range $k, $v := .Values.tritonServer.additionalEnvs }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
          {{/* Add any new env variables above this; SG injects SM_DEPLOYMENT_NAME, SM_NODE_NAME and SM_SPEC_VERSION at the bottom of the env variables list */}}
            - name: SM_DEPLOYMENT_NAME
              value: {{ $name }}
            - name: SM_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SM_SPEC_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''speechmatics.com/spec-version'']'
          ports:
            - name: triton-http
              containerPort: 8000
              protocol: TCP
            - name: triton-grpc
              containerPort: 8001
              protocol: TCP
            - name: triton-metrics
              containerPort: 8002
              protocol: TCP
          volumeMounts:
            - name: triton-license
              mountPath: "/etc/secrets"
              readOnly: true
          {{- if eq "translation" $mode }}
            - name: dshm
              mountPath: /dev/shm
          {{- end }}
          {{- with .Values.tritonServer.additionalVolumeMounts}}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tritonServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $.Values.tritonServer.enablePreStopHook }}
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  # waiting for all tcp connections to port 8001 to go away before finishing the pre stop hook
                  - |
                  {{- .Files.Get "preStop.sh" | nindent 22 }}
          {{- end}}
          {{- if ne "translation" $mode }}
          {{- with .Values.tritonServer.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tritonServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with .Values.tritonServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.inferenceSidecar.enabled }}
        - name: "inference-sidecar"
          image: {{ include "sm-gpu.image" (dict "Chart" .Chart "global" .Values.global.resourceManager "component" .Values.inferenceSidecar) | quote }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SM_METRICS_PORT
              value: {{ $inferenceSidecarPort | quote }}
            - name: REGISTER_CONDITIONS
              value: {{ $.Values.inferenceSidecar.registerConditions | quote }}
          {{- if not (or (hasKey .Values.inferenceSidecar.env "REGISTER_FEATURES") (eq "translation" $mode))}}
            - name: REGISTER_FEATURES
              value: {{ toJson (merge (include "sm-gpu.models_for_recipe" . | fromYaml ) (dict "version" (include "sm-gpu.registered_features_version" .) "partition" (default "default" .Values.inferenceSidecar.registerFeatures.partition ))) | squote }}
          {{- end }}
            - name: SM_TOKEN_STORE_URL
          {{- if $.Values.inferenceSidecar.resourceManager.configMap.enabled }}
              valueFrom:
                configMapKeyRef:
                  name: {{ default $.Release.Name $.Values.inferenceSidecar.resourceManager.configMap.name }}
                  key: resource_manager_url
          {{- else }}
              value: {{ default $.Values.global.resourceManager.url $.Values.inferenceSidecar.resourceManager.url }}
          {{- end }}
            - name: SM_CRASH_DETECTOR_DRY_RUN
              value: {{ .Values.inferenceSidecar.crashDetectorDryRun | quote }}
          {{- range $k, $v := .Values.inferenceSidecar.env }}
            - name: {{ $k }}
              value: {{ $v | squote }}
          {{- end }}
          {{/* Add any new env variables above this; SG injects SM_DEPLOYMENT_NAME, SM_NODE_NAME and SM_SPEC_VERSION at the bottom of the env variables list */}}
            - name: SM_DEPLOYMENT_NAME
              value: {{ $name }}
            - name: SM_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SM_SPEC_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''speechmatics.com/spec-version'']'
          ports:
            - name: sidecar-metrics
              containerPort: {{ $inferenceSidecarPort }}
              protocol: TCP
            {{- /* Do not change the port name as it is expected by repopulation service */}}
            - name: register-repop
              containerPort: 8022
              protocol: TCP
          {{- with .Values.inferenceSidecar.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.tritonServer.terminationGracePeriodSeconds }}
      {{- with .Values.tritonServer.runtimeClassName }}
      runtimeClassName: {{ . }}
      {{- end }}
      {{- with $.Values.tritonServer.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: triton-license
          secret:
            secretName: {{ default .Values.global.licensing.secretName .Values.tritonServer.licensing.secretName }}
            optional: false
        {{- if eq "translation" $mode }}
        # https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine
        - name: dshm
          emptyDir:
            medium: Memory
        {{- end }}
        {{- with .Values.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
